#Use root/password as user/password credentials
version: '3.3'

services:
  db:
    image: mysql
    ports:
      - "8080:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: root

  php:
    image: container-curso-pdo-jp
    build: .
    ports:
      - "80:8080"
    

#FROM php:7.4-cli
#COPY ./ /var/www/html/
#WORKDIR /var/www/html/
#CMD ["php", "-S", "0.0.0.0:8080"]
